### ISSUE TITLE
Rate Limiting for API_KEY not working.

### ISSUE THREAD

**Issue by KmiQ** [messari/messari-python-api#15]
**Problem**
Even if you are a PRO user using the API_KEY, you are rate limited as if you don't use API_KEY.

**Source of the Problem and Solution**
This looks to me like a bug in the code. The `api_dict` is not used anywhere as part of headers when elaborating/creating the requests. The `get_response(...)` function is expected a`headers` as part of its arguments but it's not passed when called in any of the API endpoint wrappers/functions. I tested this in the `get_metric_timeseries` function. I did the following change in my local:

```
Before:
response = self.get_response(url, params=payload)

After
response = self.get_response(url, params=payload, headers=self.api_dict)
```

and it worked beautifully. My requests are rate-limited now based on the API KEY. I guess a similar thing needs to be done to the rest of the functions and that should fix the problem.

**Comment by vinhloc30796** [comment]
@KmiQ this should already be fixed in https://github.com/messari/messari-python-api/commit/f5ce40f52ff20eec9492a4311a30be62a0b9d53b no?

**Comment by KmiQ** [comment]
yup, it was fixed. Closing this ticket.
